const mockupData = {
  channels: [
    {
      id: 1,
      name: "Channel 1",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel1",
      notification: 0,
    },
    {
      id: 2,
      name: "Channel 2",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel2",
      notification: 4,
    },
    {
      id: 3,
      name: "Channel 3",
      imgUrl: "",
      slugChannel: "channel3",
      notification: 2,
    },
    {
      id: 4,
      name: "Channel 4",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel4",
      notification: 1,
    },
    {
      id: 5,
      name: "Channel 5",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel5",
      notification: 99,
    },
    {
      id: 6,
      name: "Channel 6",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel6",
      notification: 54,
    },
    {
      id: 7,
      name: "Channel 7",
      imgUrl: "",
      slugChannel: "channel7",
      notification: 44,
    },
    {
      id: 8,
      name: "Channel 8",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel8",
      notification: 63,
    },
    {
      id: 9,
      name: "Channel 9",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel9",
      notification: 14,
    },
    {
      id: 10,
      name: "Channel 10",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel10",
      notification: 99,
    },
    {
      id: 11,
      name: "Channel 11",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel11",
      notification: 400,
    },
    {
      id: 12,
      name: "Channel 12",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel12",
      notification: 412,
    },
    {
      id: 13,
      name: "Channel 13",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel13",
      notification: 100,
    },
    {
      id: 14,
      name: "Channel 14",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel14",
      notification: 100,
    },
    {
      id: 15,
      name: "Channel 15",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel15",
      notification: 100,
    },
    {
      id: 16,
      name: "Channel 16",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel16",
      notification: 100,
    },
    {
      id: 21,
      name: "Channel 21",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel21",
      notification: 100,
    },
    {
      id: 17,
      name: "Channel 17",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel17",
      notification: 100,
    },
    {
      id: 18,
      name: "Channel 18",
      imgUrl: "../../public/assets/svg/bg-login.svg",
      slugChannel: "channel18",
      notification: 100,
    },
  ],
};
export default mockupData;
